# Generated by Django 4.1.1 on 2022-09-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel_app', '0002_alter_category_options_product_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
