# Generated by Django 4.1.1 on 2022-09-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel_app', '0004_alter_gallery_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='Золото', max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание товара'),
        ),
    ]
