# Generated by Django 4.1.1 on 2022-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel_app', '0005_alter_product_color_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
