# Generated by Django 4.1.1 on 2022-09-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel_app', '0009_alter_category_image_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories/', verbose_name='Иконка'),
        ),
    ]
