# Generated by Django 4.1.1 on 2022-10-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel_app', '0017_cities_favouriteproducts_profile_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='categories/', verbose_name='Иконка'),
        ),
    ]
